# -*- coding: utf-8 -*-
"""EDA-Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gMFoIyEqB6bZ2GnImc5P0SC2BEcNOhTB

# EDA NPS

# EDA Tech Challange 1 - Net Promoter Score

## 1. Introdução do Problema

### 1.1. O que é NPS?

O **Net Promoter Score (NPS)** é uma métrica amplamente utilizada para medir a satisfação e a lealdade dos clientes em relação a uma empresa, produto ou serviço. Criado por Fred Reichheld em 2003, o NPS é baseado em uma única pergunta: *"Em uma escala de 0 a 10, qual a probabilidade de você recomendar nossa empresa a um amigo ou colega?"*

Com base na nota atribuída, os clientes são classificados em três grupos:

- **Promotores (9–10):** clientes altamente satisfeitos, que tendem a recomendar a empresa e contribuir para o crescimento orgânico.
- **Neutros (7–8):** clientes satisfeitos, mas sem entusiasmo suficiente para recomendar ativamente.
- **Detratores (0–6):** clientes insatisfeitos, que podem prejudicar a reputação da empresa por meio de avaliações negativas.

O score final é calculado pela fórmula:

> **NPS = % Promotores − % Detratores**

O resultado varia de **−100** (todos detratores) a **+100** (todos promotores). Valores acima de 0 já são considerados positivos, e acima de 50 são considerados excelentes.

---

#### Problema de Negócio

Com o crescimento acelerado do e-commerce nacional, a empresa passou a lidar com um volume cada vez maior de pedidos, entregas e interações com clientes. Esse crescimento trouxe ganhos importantes de escala, mas também revelou desafios relevantes na experiência do cliente, especialmente refletidos na **alta variabilidade do NPS entre diferentes perfis de consumidores**.

A área de Experiência do Cliente identificou que, mesmo com indicadores operacionais aparentemente semelhantes, alguns clientes se tornam promotores da marca enquanto outros se tornam detratores. Atualmente, o NPS é coletado **apenas após o encerramento da jornada de compra**, o que limita a capacidade da empresa de:

- Antecipar problemas antes que afetem a satisfação;
- Priorizar ações corretivas de forma proativa;
- Atuar preventivamente para melhorar a experiência do cliente.

Nesse contexto, surge a necessidade de **transformar dados operacionais** — como informações de pedidos, logística e atendimento — em **insights acionáveis**, capazes de orientar decisões estratégicas nas áreas de logística, atendimento, produto e estratégia.

---

Essa diferença levanta uma questão central para o negócio: quais **fatores operacionais** realmente **influenciam a satisfação do cliente** e **como a empresa pode agir de forma proativa para melhorar a experiência** antes mesmo da aplicação da pesquisa de NPS?

## 2. Importação de bibliotecas e configurações iniciais
"""

#Importar as bibliotecas
import pandas as pd
import numpy as np
# bibliotecas para gráficos
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
# ferramentas do modelo preditivo
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score

# configurações padrões dos graficos
plt.style.use("default")
sns.set(style="whitegrid")

# Configuração padrão de tamanho dos gráficos
plt.rcParams["figure.figsize"] = (8, 5)
plt.rcParams["axes.titlesize"] = 12
plt.rcParams["axes.labelsize"] = 11

print("Bibliotecas carregadas com sucesso!")

"""## 3. Contexto e carregamento dos dados

"""

# Carregamento dos dados direto do GitHub
url = "https://raw.githubusercontent.com/jcdematos/fiap-iast-tech-challange-01/refs/heads/main/data/nps.csv"
df_nps = pd.read_csv(url)

# Informações gerais sobre os dados, colunas, linhas e tipo
df_nps.info()

"""### 3.1 Visão geral dos dados, podemos visualizar as colunas e entender o que temos em cada coluna."""

df_nps.head(10)

"""## 4. Estrutura do dataset"""

# Mostra dados de estatistica descritiva dos dados
# Removemos o customer_id e o order_id pois são dados de registro do banco de
# dados e de natureza sequencial

df_nps.drop(columns=['customer_id','order_id']).describe().drop('count')

"""**bold text**# New Section"""

df_nps.shape
print(f'Tamanho do nosso Dataset (Linhas, Colunas): {df_nps.shape}')

"""## 5. Qualidade dos dados

"""

# Verificando que não temos valores de NPS acima de 0 ou acima de 10
len(df_nps[(df_nps['nps_score'] < 0) | (df_nps['nps_score'] > 10)])

cols_non_negative = ['delivery_delay_days', 'complaints_count',
                     'customer_service_contacts', 'resolution_time_days']
(df_nps[cols_non_negative] < 0).sum()

"""### 5.1 Valores Nulos"""

# Verifica valores nulos
df_nps.isnull().sum()

# Verifica linhas duplicadas
df_nps.duplicated().sum()

# Verifica valores únicos
df_nps.nunique()

"""##  6. Panorama Geral do NPS

Sabe-se que um dado de interesse é o NPS Score. Iniciamos entendendo o panorama geral desta variavel, para tal, podemos questionar, dado um NPS classificado, quantas ocorrências temos de cada classe.

Notamos na parte 3, de contexto e carregamento dos dados que o NPS possui valores decimais, não inteiros. Para realizar a classificação, precisamos decidir o que fazer com esses valores.

Se entendermos que estes dados são confiáveis, os valores decimais podem ser fruto de:
- Média ou agregação de pontuações de múltiplas pesquisas
- Pontuação ajustada por alguma fórmula

##### Nota: o nps_score original possui uma casa decimal.
##### Arredondamos para inteiro pois a metodologia oficial do NPS trabalha com notas de 0 a 10 sem decimais.
##### Isso evita ambiguidade na classificação (ex: 6.7 é detrator ou neutro?)
"""

# 6.1 - Função para classificar as notas do NPS contendo valores decimais

# Helper functions
def classifica_nps(score):
  if score <= 6:
    return 'Detrator'
  elif score <= 8:
    return 'Neutro'
  else:
    return 'Promotor'

# Quantidade de notas em cada classe

df_nps['nps_class'] = df_nps['nps_score'].apply(classifica_nps)

print(df_nps['nps_class'].value_counts())

# 6.2 - Função para classificar as notas do NPS contendo valores inteiros

# Arredondar para o inteiro mais próximo (ROUND)
df_nps['nps_score_round'] = df_nps['nps_score'].apply(round)

# Classificar com base no score arredondado
df_nps['nps_class_round'] = df_nps['nps_score_round'].apply(classifica_nps)

print("\nPorcentagem de cada classe NPS (arredondamento ROUND):")
percentage_nps_round = df_nps['nps_class_round'].value_counts(normalize=True)
print(percentage_nps_round)

print("\nComparativo das porcentagens de Detratores, Neutros e Promotores:")
comparison_df = pd.DataFrame({
    'NPS_Class_Original': df_nps['nps_class'].value_counts(normalize=True) * 100,
    'NPS_Class_Round': percentage_nps_round * 100
})
print(comparison_df.sort_index())

# GRÁFICO 1 — Distribuição de Promotores, Neutros e Detratores
plt.figure(figsize= (8,4))

# Conta quantos clientes há em cada categoria e plota em barras
ordem = ['Detrator', 'Neutro', 'Promotor']
cores = ['#e74c3c', '#f39c12', '#2ecc71']  # vermelho, amarelo, verde

ax = sns.countplot(data=df_nps, x='nps_class_round', order=ordem, palette=cores)

# Adiciona o número em cima de cada barra
for p in ax.patches:
    ax.annotate(f'{int(p.get_height())}',
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha='center', va='bottom', fontsize=12)

plt.title('Distribuição de Clientes por Categoria NPS', fontsize=14)
plt.xlabel('Categoria')
plt.ylabel('Quantidade de Clientes')
plt.tight_layout()
plt.show()

# Insight para o negócio
print("Insight: 84% dos clientes são detratores — situação crítica.")

# 6.3 reordenando as colunas, trazendo a coluna com valores de NPS inteiros (round) para o lado da coluna com valores de NPS
#decimais (float)

# Lista com a ordem desejada das colunas
columns = df_nps.columns.tolist()
# Remova 'nps_score_round' da sua posição atual
columns.remove('nps_score_round')
# Encontre o índice de 'nps_score'
idx = columns.index('nps_score')
# Insira 'nps_score_round' após 'nps_score'
columns.insert(idx + 1, 'nps_score_round')
# Reordene o DataFrame
df_nps = df_nps[columns]

print("DataFrame com 'nps_score_round' após 'nps_score':")
print(df_nps.head())

# 6.4 Histograma do NPS

sns.histplot(df_nps["nps_score"], bins=30, kde=True)
plt.title("Distribuição do NPS")
plt.xlabel("NPS Score")
plt.ylabel("Frequência")
plt.tight_layout()
plt.show()

# 6.4 Histograma do NPS removendo-se os zeros

sns.histplot(df_nps[df_nps["nps_score"] > 0]["nps_score"], bins=30, kde=True)
plt.title("Distribuição do NPS (sem zeros)")
plt.xlabel("NPS Score")
plt.ylabel("Frequência")
plt.tight_layout()
plt.show()

# 6.5 Boxplot geral do NPS

sns.boxplot(x=df_nps["nps_score"])
plt.title("Boxplot do NPS Score")
plt.xlabel("NPS Score")
plt.tight_layout()
plt.show()

# 6.6 Medidas resumo do NPS

df_nps["nps_score"].agg(["mean", "median", "min", "max"])

"""Realizando um gráfico de correlação de Pearson podemos observar as variáveis que possuem correlação entre si. Notamos que uma grande parte das variáveis dos nossos dados não possuem correlação."""

corr = df_nps.drop(columns=['customer_id','order_id','nps_class','nps_class_round','customer_region', 'customer_age']).corr()

plt.figure(figsize=(14,10))
sns.heatmap(corr, annot=True, fmt='.2f', cmap='coolwarm', center=0,
              mask=np.triu(np.ones_like(corr, dtype=bool)))
plt.title('Correlation Matrix')

plt.show()

"""Porém, há um conjunto delas que mostram forte relação, podemos elaborar um gráfico de correlação apenas com essas variáveis."""

cols = ['nps_score', 'delivery_delay_days', 'customer_service_contacts',
        'resolution_time_days', 'csat_internal_score', 'complaints_count', 'repeat_purchase_30d']

corr = df_nps[cols].corr()

plt.figure(figsize=(9, 7))
sns.heatmap(corr, annot=True, fmt='.2f', cmap='rocket', center=0,
            mask=np.triu(np.ones_like(corr, dtype=bool)))
plt.title('Correlation Matrix')
plt.tight_layout()
plt.show()

cols = ['nps_score', 'delivery_delay_days', 'complaints_count', 'customer_service_contacts',
        'resolution_time_days', 'csat_internal_score', 'repeat_purchase_30d']

corr_with_nps = df_nps[cols].corr()['nps_score'].drop('nps_score').abs().sort_values(ascending=False)
print(corr_with_nps)

"""### 7. Explorando as variáveis correlacionadas ao NPS

Entende-se que algumas das variáveis que mostram forte correlação com o NPS não entram no contexto de solução do problema, pois são conhecidas apenas após o fluxo de compra.

Sendo elas:
- Resolution time days: Conhecida apenas após a solução do problema/ticket. Portanto, não pode ser um indicador do NPS.
- Repeat Purchase 30d: Também é conhecida apenas no fim do processo e para clientes que já realizaram compras anteriores.
"""

#Correlação das variáveis com o NPS
cols_corr = ['delivery_delay_days', 'customer_service_contacts', 'csat_internal_score', 'complaints_count']

# Calcula a correlação de cada variável com o nps_score
correlacoes = df_nps[cols_corr + ['nps_score']].corr()['nps_score'].drop('nps_score')
correlacoes = correlacoes.sort_values()

# Define cor: vermelho se negativo, verde se positivo
cores_corr = ['#e74c3c' if v < 0 else '#2ecc71' for v in correlacoes]

plt.figure(figsize=(10,5))
correlacoes.plot(kind='barh', color=cores_corr)
plt.axvline(0, color='black', linewidth=0.8)
plt.title('Correlação das Variáveis com o NPS Score', fontsize=14)
plt.xlabel('Correlação')
plt.tight_layout()
plt.show()

"""### 7.1. Entendendo a correlação por região

Como região não é uma variável númerica, não podemos analisa-la através da correlação. Portanto, iremos investigar se há relação do NPS com região.
"""

# Validar se o NPS é influenciado por região

nps_by_region = df_nps.groupby('customer_region')['nps_class'].value_counts(normalize=True).unstack(fill_value=0) * 100

# Calcular o NPS usando a fórmula: % Promotores - % Detratores
nps_by_region['NPS'] = nps_by_region['Promotor'] - nps_by_region['Detrator']

print("NPS por Região:")
print(nps_by_region[['Promotor', 'Neutro', 'Detrator', 'NPS']].sort_values(by='NPS', ascending=False))

import plotly.express as px

nps_by_region = df_nps.groupby('customer_region')['nps_class'].value_counts(normalize=True).unstack(fill_value=0) * 100
nps_by_region['NPS'] = nps_by_region['Promotor'] - nps_by_region['Detrator']
nps_by_region = nps_by_region['NPS'].sort_values().reset_index()
nps_by_region.columns = ['Região', 'NPS']

fig = px.bar(
    nps_by_region,
    width=800,
    height=500,
    x='Região',
    y='NPS',
    color='NPS',
    color_continuous_scale=['steelblue' , 'steelblue'],
    title='NPS Score por Região',
    labels={'NPS': 'NPS Score (%)'},
    text='NPS'
    )

fig.update_traces(texttemplate='%{text:.1f}%', textposition='outside')
fig.add_hline(y=0, line_dash='dash', line_color='black', line_width=1)
fig.update_layout(coloraxis_showscale=False)

fig.show()

"""Notamos que apesar de um NPS ligeiramente maior no sul, ainda é um NPS significativamente negativo, de forma que região não é um fator decisivo na nota no NPS, não há uma região puxando para baixo a nota do NPS que poderia indicar algum problema de logística localizado.

### 7.2. Delivery Delay Days

#### Impacto do Atraso na Entrega sobre o NPS

O atraso na entrega é o fator com maior correlação negativa com o
NPS. A análise revela um padrão claro de tolerância por
perfil de cliente:

- 🟢 **Promotores** desaparecem a partir de 5 dias de atraso
- 🟡 **Neutros** resistem até 4 dias antes de virarem detratores
- 🔴 **Detratores** estão presentes em todos os níveis de atraso

**Ponto de ruptura:** a partir de 6 dias, a base é 100% detratores.
"""

sns.histplot(data = df_nps, x = "delivery_delay_days", y = "nps_score", hue="nps_class",
             palette={'Detrator': 'red', 'Neutro': 'gold', 'Promotor': 'green'})
plt.title("Distribuição do NPS")
plt.xlabel("delivery_delay_days")
plt.ylabel("NPS Score")
plt.tight_layout()
plt.show()

"""### O atraso como ponto de ruptura
A tabela revela um padrão claro de tolerância ao atraso por perfil de cliente.
Promotores desaparecem a partir de 5 dias de atraso. Neutros a partir de 5 dias também. Detratores persistem em todos os níveis — inclusive quando não há atraso.

O ponto crítico está entre 2 e 4 dias: é nessa faixa que promotores e neutros migram para detratores de forma acelerada.

Conclusão: a partir de 5 dias de atraso, a empresa só tem detratores. Esse é o ponto de ruptura irreversível da experiência do cliente.
"""

df_nps.groupby(['delivery_delay_days', 'nps_class']).size().unstack(fill_value=0)

# Ponto de rupturadel delivery delay days
avg_nps = df_nps.groupby('delivery_delay_days')['nps_score'].mean().round(2)
delay_df = avg_nps.to_frame()
delay_df['drop'] = delay_df['nps_score'].diff().round(2)
delay_df['drop'] = delay_df['drop'].apply(lambda x: f"{x:+.2f}" if pd.notna(x) else "—")

print(delay_df)

"""### 7.3. Complaints Counts

### Impacto do Número de Reclamações sobre o NPS

O número de reclamações é o segundo fator com maior correlação
negativa com o NPS. O padrão é semelhante ao do atraso,
mas com uma diferença importante:

- 🟢 **Promotores** resistem até 3 reclamações, com 75% dos promotores com 3 ou menos reclamações. Sendo que não existem promotores após cinco reclamções (exceto outliers).
- 🟡 **Neutros** resistem até 4 reclamações, com 75% dos promotores com 3 ou menos reclamações.
- 🔴 **Detratores** dominam a partir de 6 reclamações

**Diferença em relação ao atraso:** enquanto o atraso elimina
promotores rapidamente, o número de reclamações tem um comportamento
mais irregular — há promotores mesmo com muitas reclamações.
Isso sugere que **o que importa não é só quantas reclamações
o cliente fez, mas se elas foram resolvidas.**

**Conclusão:** reclamações mal resolvidas são mais danosas
ao NPS do que o volume de reclamações em si.
"""

# Histograma complains count
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

sns.histplot(data = df_nps, x = "complaints_count", y = "nps_score", hue="nps_class",
             palette={'Detrator': 'red', 'Neutro': 'gold', 'Promotor': 'green'},
             ax=axes[0])
axes[0].set_title("Distribuição do NPS")
axes[0].set_xlabel("complaints_count")
axes[0].set_ylabel("NPS Score")
start, end = 0, 11
axes[0].set_xticks(np.arange(start, end + 1, 1))

sns.boxplot(data=df_nps, x="nps_class", y="complaints_count", hue="nps_class",
            palette={'Detrator': 'red', 'Neutro': 'gold', 'Promotor': 'green'},
            order=['Promotor', 'Neutro', 'Detrator'],
            ax=axes[1])
axes[1].set_title("Complaints Count por Classe NPS")
axes[1].set_xlabel("Classe NPS")
axes[1].set_ylabel("Complaints Count")
plt.show()

"""As reclamações como ponto de ruptura

A tabela revela um padrão claro da tolerância ao número de reclamações por perfil de cliente.

- Promotores desaparecem a partir de 4 reclamações.
- Neutros a partir de 6.
- Detratores começam a surgir a partir de 2 reclamações, e a média começa a estabilizar após 4 reclamações.

O ponto crítico está entre 2 e 4 reclamações: é nessa faixa que promotores e neutros migram para detratores de forma acelerada.

Conclusão: a partir de 2 reclamações a média do NPS em relação à complaints cai para detratora, e a partir de 5 os clientes migram para detratores.
"""

df_nps.groupby(['complaints_count', 'nps_class']).size().unstack(fill_value=0)

# Ponto de ruptura complaints count
avg_nps = df_nps.groupby('complaints_count')['nps_score'].mean().round(2)
complaint_df = avg_nps.to_frame()
complaint_df['drop'] = complaint_df['nps_score'].diff().round(2)
complaint_df['drop'] = complaint_df['drop'].apply(lambda x: f"{x:+.2f}" if pd.notna(x) else "—")

print(complaint_df)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

sns.scatterplot(data=df_nps, x="delivery_delay_days", y="nps_score", alpha=0.5, ax = axes[0], hue="nps_class",
             palette={'Detrator': 'red', 'Neutro': 'gold', 'Promotor': 'green'})

# Linha de tendência com regplot
sns.regplot(
         data=df_nps,
        x="delivery_delay_days",
        y="nps_score",
        scatter=False,            # não recria os pontos
        color="red",              # linha de tendência em vermelho
        line_kws={"linewidth": 2}, # deixa a linha mais grossa
        ax = axes[0]

    )
axes[0].set_title("Relação entre nps_score x delivery_delay_days")
plt.title("Relação entre nps_score x delivery_delay_days")
plt.xlabel("delivery_delay_days")
plt.ylabel("nps_score")
plt.tight_layout()

# 2º grafico
sns.scatterplot(data=df_nps, x="complaints_count", y="nps_score", alpha=0.5, ax = axes[1], hue="nps_class",
             palette={'Detrator': 'red', 'Neutro': 'gold', 'Promotor': 'green'})

# Linha de tendência com regplot
sns.regplot(
         data=df_nps,
        x="complaints_count",
        y="nps_score",
        scatter=False,            # não recria os pontos
        color="red",              # linha de tendência em vermelho
        line_kws={"linewidth": 2}, # deixa a linha mais grossa
        ax = axes[1]
    )
axes[1].set_title("Relação entre nps_score x complaints_count")
plt.title("Relação entre nps_score x complaints_count")
plt.xlabel("complaints_count")
plt.ylabel("nps_score")
plt.tight_layout()
plt.show()

"""### 7.4 Média por Perfil de Clientes

Analisando a média por perfil de clientes, considerando pouco atraso e baixa número de reclamações dado a base de dados, conseguimos identificar que o cliente com a melhor nota de NPS é o que possui um pouco atraso em conjunto com baixo número de reclamações.
"""

# Define groups
low_delay      = df_nps['delivery_delay_days'] < 4
low_complaints = df_nps['complaints_count'] < 4

groups = {
    'Média Atraso < 4 dias':               df_nps[low_delay]['nps_score'].mean(),
    'Média Reclamações < 4':           df_nps[low_complaints]['nps_score'].mean(),
    'Média Atraso e Reclamações':    df_nps[low_delay & low_complaints]['nps_score'].mean(),
    'Média Geral':               df_nps['nps_score'].mean(),
}

# Print table
print("Avg NPS Score by Group:")
print("-" * 40)
for group, avg in groups.items():
    print(f"  {group:<30} {avg:.2f}")

# Plot
plt.figure(figsize=(8, 5))
plt.bar(groups.keys(), groups.values(), color=['steelblue', 'coral', 'seagreen', 'gray'])
plt.title('Média NPS Score — Atraso Reduzido vs Reclamações Reduzidas vs Ambos')
plt.ylabel('Média do NPS Score')
plt.xticks(rotation=15, ha='right')
plt.axhline(df_nps['nps_score'].mean(), color='black', linewidth=0.8, linestyle='--', label='Média Geral')
plt.legend()
plt.tight_layout()
plt.show()

"""## 8. Consolidação

### Quais fatores parecem mais críticos para a satisfação?

Através da exploração dos dados, nota-se algumas variáveis com alta correlação com a variável de interesse (NPS Score), porém, o problema em questão lida com os fatores operacionais durante a jornada e algumas das variáveis são indicadores no fim da jornada, próximo ao NPS.

Dois fatores que possuem alta correlação com o NPS são os atrasos na entrega e o número de reclamações dos clientes com o suporte, sendo:

- Atraso de entrega, registrado por 'delivery_delay_days', sendo um fator logístico;
- A quantidade de reclamações, registrado pelo 'complaints_counts', sendo um fator de atendimento.

### O que mais gera detratores?

A principal causa de detratores são os atrasos, apenas um dia de atraso já leva a média do NPS para o nível de detrator, após três dias de atraso na entrega todos os clientes passam a ser neutros ou detratores.

Assim como o número de reclamações, considerando clientes com 0 reclamações, o NPS médio é de 8.5, após duas reclamações, o NPS cai para 6.

### Existe algum “ponto de ruptura” na experiência do cliente?

Temos um ponto de ruptura para o delivery_delay_days, entre 2 a 4 dias de entrega é o ponto onde os clientes passam de promotores e neutros para detratores de forma acelerada.

Algo similar ocorre para o complaints_counts, em que a média do NPS em relação aos números de reclamações cai para níveis de detrator após 2 reclamações, e após 5 reclamações a grande maioria dos clientes já estão como detratores.

### Que tipo de cliente tende a ter NPS mais alto ou mais baixo?

Clientes com pouco atraso e baixo número de reclamações são os clientes com o maior NPS, os clientes com ambas as características baixas são os clientes com o NPS mais alto.


Clientes com muito atraso em seus pedidos são os com nota de NPS mais baixo.
"""

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score, f1_score
from imblearn.over_sampling import SMOTE

# Binary target — Detrator vs Não Detrator
df_nps['nps_binary'] = df_nps['nps_class'].apply(
    lambda x: 'Detrator' if x == 'Detrator' else 'Não Detrator'
)

print("Class distribution:")
print(df_nps['nps_binary'].value_counts())
print(f"\n% Detrator:     {(df_nps['nps_binary'] == 'Detrator').mean()*100:.1f}%")
print(f"% Não Detrator: {(df_nps['nps_binary'] == 'Não Detrator').mean()*100:.1f}%")

features = ['delivery_delay_days', 'complaints_count']

X = df_nps[features]
y = df_nps['nps_binary']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

sm = SMOTE(random_state=42)
X_train_res, y_train_res = sm.fit_resample(X_train, y_train)

classifiers = {
    'Logistic Regression': LogisticRegression(max_iter=1000, random_state=42, class_weight='balanced'),
    'Random Forest':       RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced'),
    'Gradient Boosting':   GradientBoostingClassifier(n_estimators=100, random_state=42)
}

for name, clf in classifiers.items():
    clf.fit(X_train_res, y_train_res)
    y_pred = clf.predict(X_test)

    print(f"\n{'='*55}")
    print(f"  {name}")
    print(f"{'='*55}")
    print(f"  Accuracy:       {accuracy_score(y_test, y_pred):.4f}")
    print(f"  F1 (macro):     {f1_score(y_test, y_pred, average='macro'):.4f}")
    print(f"  F1 (weighted):  {f1_score(y_test, y_pred, average='weighted'):.4f}")
    print()
    print(classification_report(y_test, y_pred))

